services:
  db:
    image: postgres:17-alpine
    container_name: deokhugam-postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: deokhugam
      POSTGRES_USER: team4
      POSTGRES_PASSWORD: deokhugam4!
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: deokhugam-redis
    ports:
      - "6379:6379"

  influxdb:
    image: influxdb:1.8
    container_name: deokhugam-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: deokhugam-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb