server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: validate


logging:
  level:
    root: WARN
    com.sprint.mission.discodeit: INFO

