server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: validate


logging:
  level:
    root: WARN
    com.part3_team4.deokhoogam: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration_time: 3600000