spring:
  application:
    name: deokhugam
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  batch:
    job:
      enabled: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_S3_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000




logging:
  level:
    root: INFO

naver:
  client:
    id: ${NAVER_ID:}
    secret: ${NAVER_SECRET:}

ocr:
  space:
    api-key: ${OCR_SPACE_API_KEY:dummy_key}
    connect-timeout: 5000
    read-timeout: 15000

cache:
  ranking:
    enabled: true


